[string]$ecapDir = "C:\dev\energycap"
[string]$ecapIdDir = "C:\dev\energycapid\src\EnergyCAPIDAPI.Web"
[string]$desktopDir = "C:\Users\lukef\Desktop"
[string]$ngrokDir = "C:\Users\lukef\ngrok"
[string]$ghostInspectorApiKey = "382ac9bf073d5431c1dbfa9f5a684ced3a1bcb51"
[string]$ngrokAuthToken = "6ecAy2ok6bUz3w15c7YPA_3N9Cnn5GweVhKseJsK6T6"
